package gov.cpsc.hts.itds.ui.service.exceptions;

public enum CpscHtsMgmtCodeEnum {

	DEFAULT, WATCH, OK, EXCEPTION_PARSING_LINE, EXCEPTION_PARSING_INDENT, EXCEPTION_INSERTING_TO_SCRATCH_TABLE, EXCEPTION_DURING_UPLOAD, 
	EXCEPTION_WRITING_TO_LOOKUP_TABLE, EXCEPTION_RECORDING_HISTORY, SAW_RESET_FLAG, 
	EXCEPTION_GETTING_PROPERTY, EXCEPTION_INVALID_TRANSITION_REQUEST, EXCEPTION_READING_FILE, EXCEPTION_WRITING_TO_FILE_TABLE
    
}
